open_base:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 30

    left_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_left_joint
        pid: {p: 1, i: 10, d: 0.0001}

    back_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_back_joint
        pid: {p: 1, i: 10, d: 0.0001}

    right_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_right_joint
        pid: {p: 1, i: 10, d: 0.0001}
