open_base:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 30

    left_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_left_joint
        pid: {p: 0.1, i: 50, d: 0.0001, i_clamp_max: 100.0, i_clamp_min: -100.0}

    back_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_back_joint
        pid: {p: 0.1, i: 50, d: 0.0001, i_clamp_max: 100.0, i_clamp_min: -100.0}

    right_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: rim_right_joint
        pid: {p: 0.1, i: 50, d: 0.0001, i_clamp_max: 100.0, i_clamp_min: -100.0}

