# range settings
obstacle_range: 3 # lidar range
raytrace_range: 12 # clear the overlapped obstacles on the path, only for the obstacle layer

# hexagonal footprint
# footprint: [[0,0.15],[0.1299,0.075],[0.1299,-0.075],[0,-0.15],[-0.1299,-0.075],[-0.1299,0.075]]
robot_radius: 0.3

# map info
map_topic: map
subscribe_to_updates: true
update_frequency: 2.0  # frequency to update costmap
publish_frequency: 5.0 # frequency to publish the new costmap to Rviz

# Choose which layer to use. ( The order of layers matters !!! )
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}  
  # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"} 
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
# Layer parameters
static_layer:
  enabled: true
  map_topic: map
  subscribe_to_updates: false
  trinary_costmap: false
  lethal_cost_threshold: 100
  update_frequency: 5.0

obstacle_layer:
  enabled: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}

inflation_layer:
  enabled: true
  inflation_radius: 1.0
  cost_scaling_factor: 3.0
