map_update_interval: 3
maxUrange: 16.0
maxRange: 16.0  
sigma: 1.0
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 4
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: -200
srr: 0.15
srt: 0.15
str: 0.15
stt: 0.15
linearUpdate: 0.2
angularUpdate: 0.05
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 100
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.03
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
transform_publish_period: 0.02